# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen =
NAME = aaa_diameter.so
LIBS += -lfdproto -lfdcore
extra_sources = app_opensips/avps.c app_opensips/dict_dcca.c app_opensips/dict_dcca_3gpp.c app_opensips/dict_nasreq.c

include ../../Makefile.modules
